/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    PatientHistory: typeof import('./src/components/PatientHistory.vue')['default']
    PatientManagement: typeof import('./src/components/PatientManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemSettings: typeof import('./src/components/SystemSettings.vue')['default']
    VisitManagement: typeof import('./src/components/VisitManagement.vue')['default']
  }
}
